product/urls.py
from django.urls import path
from .views import *

 
app_name ="product"
urlpatterns = [
    path('', main, name="main"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('<int:product_id>/create_review', create_review, name="create_review"),
    path('<int:review_id>/update_review', update_review, name="update_review"),
    path('<int:review_id>/delete_review', delete_review, name="delete_review"),
    path('<int:product_id>/product_like', product_like, name="product_like"),
    path('like_list/', like_list, name="like_list"),
]    

shoppingmall/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', main, name="main"),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    title = models.CharField(max_length= 50, null=False)
    content = models.TextField()
    price = models.CharField(max_length= 50, null=False)
    stock = models.CharField(max_length= 50, null=False)
    image = models.ImageField(upload_to='images/', null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    view_count = models.IntegerField(default = 0, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name="like_user_set", through="Like")

    @property
    def like_count(self):
        return self.like_user_set.count()


class Review(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'product'))

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Review
from django.contrib.auth.decorators import login_required

def new(request):
    return render(request, 'product/new.html')


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        image = request.FILES.get('image')
        writer = request.user
        Product.objects.create(title=title, content=content, price=price, stock=stock, image=image, writer=writer)
        return redirect('product:main')


def main(request):
    products = Product.objects.all()
    return render(request, 'product/main.html', {'products':products})


def show(request, id):
    product = Product.objects.get(pk=id)
    product.view_count += 1
    product.save()
    all_reviews = product.reviews.all().order_by('-created_at')
    return render(request, 'product/show.html', {'product': product, 'reviews':all_reviews})


def update(request,id):
    product = get_object_or_404(Product,pk=id)
    if request.method == "POST":
        product.title = request.POST['title']
        product.content = request.POST['content']
        product.price = request.POST['price']
        product.stock = request.POST['stock']
        product.image = request.FILES.get('image')
        product.save()
        return redirect('product:show', product.id)
    return render(request,'product/update.html',{'product':product})


def delete(request, id): 
	product = get_object_or_404(Product, pk=id) 
	product.delete()
	return redirect("product:main")

def create_review(request, product_id):
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        current_user = request.user
        review_content = request.POST.get('content')
        Review.objects.create(content=review_content, writer=current_user, product=product)
    return redirect('product:show', product_id)


def update_review(request, review_id): 
    review = get_object_or_404(Review, pk=review_id)
    if request.method == "POST":
        review.content = request.POST['content']
        review.save()
        return redirect('product:show', review.product.id)
    return render(request,'product/review_update.html',{'review':review})


def delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    review.delete()
    return redirect('product:show', review.product.id) 


@login_required
def product_like(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.user in product.like_user_set.all():
        product.like_user_set.remove(request.user)
    else:
        product.like_user_set.add(request.user)

    if request.GET.get('redirect_to') == 'show':
        return redirect('product:show', product_id)
    else:
        return redirect('product:main')


@login_required
def like_list(request):
    likes = Like.objects.filter(user=request.user)
    return render(request, 'product/like_list.html', {'likes':likes})

shoppingmall/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

product/templates/product/like_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
    <div class="container">
        <h1>좋아요를 누른 글 목록</h1>
        <a class="btn btn-outline-dark" href="{% url 'product:new' %}">상품 등록</a>
        <div class="row">
            {% for like in likes %}
            <div class="col-md-4 col-12">
                <div class="card" style="width: 18rem; margin-top: 20px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ like.product.title }}</h5>
                        <p>조회수 : {{ like.product.view_count }}</p>
                        <a href="{% url 'product:show' like.product.pk %}" class="btn btn-primary">상세보기</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
        <h3>로그인 후 이용이 가능합니다</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
</div>
{% endblock %}

product/templates/product/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    {% if user.is_authenticated %}
    <div class="container">
        <h1>상품 목록입니다</h1>
        <a class="btn btn-outline-dark" href="{% url 'product:new' %}">상품 등록</a>
        <div class="row">
            {% for product in products %}
            <div class="col-md-4 col-12">
                <div class="card" style="width: 18rem; margin-top: 20px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.title }}</h5>
                        <p class="card-text">{{ product.price }}</p>
                        <p class="card-text">{{ product.stock }}</p>
                        <p>{{ product.created_at }}</p>
                        <p>조회수 : {{ product.view_count }}</p>

                        <a href="{% url 'product:product_like' product.id %}">
                            {% if user in product.like_user_set.all %}
                                <i class="fas fa-heart"></i>
                            {% else %}
                                <i class="far fa-heart"></i>
                            {% endif %}
                        </a>
                        <a href="{% url 'product:show' product.pk %}" class="btn btn-primary">상세보기</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
        <h3>로그인 후 이용이 가능합니다</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
</div>
{% endblock %}

product/templates/product/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
    상품 등록하기
    </h1>
    <form action="{% url 'product:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>설명</label>
            <textarea class="form-control" name="content"></textarea>
        <div class="form-group">
            <label>가격</label>
            <textarea class="form-control" name="price"></textarea>
        <div class="form-group">
            <label>재고</label>
            <textarea class="form-control" name="stock"></textarea>    
        </div>
        <input type="file" name="image" accept="image/*">
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

product/templates/product/review_update.html
{% extends 'base.html' %}
{% block content %}


<div class="container mt-5">
    <form class="form-row" action="{% url 'product:update_review' review.id %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control col-11 mr-2" name="content" placeholder="리뷰 내용 입력...">{{ review.content }}</textarea>
        <input type="submit" class="btn btn-primary" value="확인">
    </form>
</div>

{% endblock %}

product/templates/product/show.html
{% extends 'base.html' %}
{% block content %}
<div class = container>
	<h1>상세보기 페이지</h1>
	<h3>상품명 : {{ product.title }} </h3><br>
	<h3>설명 : {{ product.content }} </h3><br>
	<h3>가격 : {{ product.price }} </h3><br>
	<h3>재고 : {{ product.stock }} </h3><br>

{% if product.writer %}
	{% if "user" in product.writer.username %}
		<h3>판매자 : {{ product.writer.last_name }} {{ product.writer.first_name }}</h3><br>
	{% else %}
		<h3>판매자 : {{ product.writer }}</h3><br>
	{% endif %}
{% else %}
	<h3>판매자 : 알 수 없음</h3>
{% endif %}

	<h3>작성 시각 : {{ product.created_at }} </h3><br>
	<h3>수정 시각 : {{ product.updated_at }} </h3><br>
	<h3>조회수: {{product.view_count }}</h3><br>

	{% if product.image %}
		<img src ="{{ product.image.url }}" width="200px", height="200px" alt="">
	{%  endif %}

	{% if user == product.writer %}
		<a href="{% url 'product:update' product.pk %}" class="btn btn-primary">수정하기</a>
		<a href = "{% url 'product:delete' product.pk %}" class="btn btn-danger">삭제하기</a>
	{% endif %}

	<div class="container mt-5">
		<form class="form-row" action="{% url 'product:create_review' product.id %}" method="POST">
			{% csrf_token %}
			<textarea class="form-control col-11 mr-2" name="content"
	placeholder="리뷰 내용 입력..."></textarea>
			<input type="submit" class="btn btn-primary" value="확인">
		</form>
	</div>

	<a href="{% url 'product:product_like' product.id %}?redirect_to=show">
		{% if user in product.like_user_set.all %}
			<i class="fas fa-heart"></i>
		{% else %}
			<i class="far fa-heart"></i>
		{% endif %}
	</a><br>

	<p>
		{{ product.like_count }}명이 좋아합니다.
	</p>
	<br>
	<p>좋아요를 누른 유저:</p>
	{% for like_user in product.like_user_set.all %}

	{% if "user" in like_user.username %} <!-- user 라는 단어가 좋아요 누른 유저의 username에 포함되어 있을 경우 -->
		{{ like_user.last_name }} {{ like_user.first_name }} <!-- 구글 소셜로그인이기 때문에 성+이름으로 표시 -->
	{% else %}
		{{ like_user.username }}
	{% endif %}

	{% endfor %}
	
	<div class="container mt-5 mb-5">
		{% for review in reviews %}
		<div class="card">
			<div class="card-body">
				{% if review.writer.username == 'user' %}
				<b>{{ review.writer.last_name }}{{ review.writer.first_name }}
					{% else %}
					<b>{{ review.writer }}</b> {% endif %} : {{ review.content }}</br>
					<small>{{ review.created_at }}</small>
					{% if user == review.writer %}
						<a href="{% url 'product:update_review' review.id %}" class="btn btn-primary">수정하기</a>
						<a href="{% url 'product:delete_review' review.id %}" class="btn btn-danger">삭제하기</a>
					{% endif %}
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

product/templates/product/update.html
{% extends 'base.html' %}
 {% block content %}
 <div class="container"> 
	<h1> 수정하기 </h1> 
	<form action="{% url 'product:update' product.id %}" method="POST" enctype="multipart/form-data"> 
		{% csrf_token %} 
		<div class="form-group">
			 <label>상품명</label> 
			<input type="text" class="form-control" name="title" value = "{{ product.title }}"> 
		</div>
		 <div class="form-group">
			 <label>설명</label>
			 <textarea class="form-control" name="content"> {{ product.content }} </textarea>
         </div>
        <div class="form-group">
            <label>가격</label> 
        <input type="text" class="form-control" name="price" value = "{{ product.price }}"> 
        </div>
        <div class="form-group">
            <label>재고</label> 
        <input type="text" class="form-control" name="stock" value = "{{ product.stock }}"> 
        </div>
        <input type="file" name="image" accept="image/*"> 
 		<input type="submit" value="글 수정" class="btn btn-outline-primary">
	 </form> 
</div>
 {% endblock %}

shoppingmall/templates/accounts/login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% providers_media_js %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

shoppingmall/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    
    <title>현이마켓</title>

    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
  </head>
  <body>
    <h1>현이마켓</h1>
    
    {% include 'shared/_navbar.html' %}

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  </body>
</html>

shoppingmall/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1> 합리적인 가격, 합리적인 품질!</h1>
<img src="{% static 'images/welcome.jpg' %}" alt="환영 이미지">
{% endblock %}

shoppingmall/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">메인</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'product:new' %}"> 상품 등록 <span class="sr-only">(current)</span></a>
        <a class="nav-link active" href="{% url 'product:main' %}"> 상품 목록 <span class="sr-only">(current)</span></a>
        <a class="nav-link active" href="{% url 'product:like_list' %}"> 좋아요 목록 <span class="sr-only">(current)</span></a>
      </div>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
          <div class="dropdown-menu">
            {% if user.is_authenticated %} {# 유저가 로그인 중이면 #}
              <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
              <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            {% endif %}
          </div>
        </li>
      </ul>    
  </nav>